trigger:
  - staging

resources:
  - repo: self

variables:
  dockerRegistryServiceConnection: '0084ee1e-f5cb-45da-a945-ea3e1d1502a4'
  imageRepository: 'backendscala'
  containerRegistry: 'blindnet.azurecr.io'
  dockerfilePath: 'Dockerfile'
  tag: '$(Build.BuildId)'
  vmImageName: 'ubuntu-latest'

stages:
  - stage: Build
    displayName: Build and push stage
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: $(vmImageName)
        steps:
          - script: |
              wget http://apt.typesafe.com/repo-deb-build-0002.deb
              sudo dpkg -i repo-deb-build-0002.deb
              sudo apt-get update
              sudo apt-get install sbt
            displayName: Install SBT
          - script: sbt assembly
            displayName: Assembly
          - task: Docker@2
            displayName: Build Docker image
            inputs:
              command: build
              repository: $(imageRepository)
              dockerfile: $(dockerfilePath)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)
              arguments: '--build-arg BN_ENV=staging'
          - task: Docker@2
            displayName: Push Docker Image
            inputs:
              command: push
              repository: $(imageRepository)
              containerRegistry: $(dockerRegistryServiceConnection)
              tags: $(tag)
